### ISSUE TITLE
Regarding the citation of CATs

### ISSUE THREAD

**Issue by SunghwanHong** [ShuaiyiHuang/SCorrSAN#1]
Hi,
Congrats for the acceptance to ECCV'22!
I was reading through the paper, and found that the citation for CATs seems to be wrong (it is instead citing VAT, which is an arxiv preprint) .  Please correct it for us!
Thanks.

**Comment by ShuaiyiHuang** [comment]
Hi Sunghwan,

Thank you very much and we are sorry for the wrong citation! We will correct it ASAP!

Thanks.
